.{
    // This file is generated by tools/download_ucd_tables.py
    //
    // Do not edit it manually!
    .unicode_version = "${version}",
    .digit_ranges = .{
$digit_ranges
    },
    .word_ranges = .{
$word_ranges
    },
    .whitespace_ranges = .{
$whitespace_ranges
    },
    .case_folds = .{
$case_folds
    },
}