name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: "0.16.0"
      - name: Build
        run: zig build
      - name: Run unit tests
        run: zig build test_unit --summary all --verbose
      - name: Run integration tests
        run: zig build test_lib --summary all --verbose
